### ISSUE TITLE
Mistral checkpoints available for local use?

### ISSUE THREAD

**Issue by Jaakko-cyber** [climate-nlp/climate-obstruction-narratives#1]
Hi!
I found your repo through https://nlp4climate.github.io/ - it seems very exciting. I would love to know if you have the fine-tuned weights-file available for mistral 7b that I could tinker around with?

Looking forward!
Jaakko

**Comment by climate-nlp** [comment]
We do not fine-tune the Mistral model. Please read README and our paper.
